name: Build and push container image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_CONFIG: $HOME/.docker
      HUB: logodev

    steps:
      - name: Maximize build space
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'

      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            **.bash
            **.py
            **.r
            **.R
            **.sh
            **.txt
            **.toml
            **.yaml
            **.yml
            Dockerfile
            infra-requirements.txt
            Pipfile**
            postBuild
            requirements.txt
            setup.py
            start
          files_ignore: |
            .github/**
            images/**

      - name: Log in to GAR
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: docker/login-action@v1
        with:
          registry: us-central1-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GAR_SECRET_KEY }}

      - name: Build the image and push to artifact registry
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: jupyterhub/repo2docker-action@master
        with:
          # Make sure username & password/token pair matches your registry credentials
          DOCKER_REGISTRY: us-central1-docker.pkg.dev
          IMAGE_NAME: ucb-datahub-2018/user-images/logodev-user-image
          # Disable pushing a 'latest' tag, as this often just causes confusion
          # LATEST_TAG_OFF: true
          # Put repo contents in /srv/repo, rather than the default (/home/jovyan). The home directory
          # is mounted over by persistent storage when we are using the built image in a JupyterHub, and
          # so all contents put in /home/jovyan are lost. This particularly prevents any 'start' script from
          # working, as it is needed in runtime.
          REPO_DIR: /srv/repo

      # Lets us monitor disks getting full as images get bigger over time
      - name: Show how much disk space is left
        run: df -h
