name: Create datahub PR
on:
  workflow_run:
      workflows: ['Build and push container image']
      types: [completed]
      branches:
        - main

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Test if vars works
    run: |
      echo "with vars:"
      echo ${{ vars.HUB }}
      echo "no vars:"
      echo ${HUB}
    # For biggish images, github actions runs out of disk space.
    # So we cleanup some unwanted things in the disk image, and reclaim that space for our docker use
    # https://github.com/actions/virtual-environments/issues/2606#issuecomment-772683150
    # and https://github.com/easimon/maximize-build-space/blob/b4d02c14493a9653fe7af06cc89ca5298071c66e/action.yml#L104
    # This gives us a total of about 52G of free space, which should be enough for now
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      run: |
        echo "Free space:"
        df -h

    - name: Checkout files in repo
      uses: actions/checkout@v4
      with:
        repository: 'berkeley-dsep-infra/datahub'
        sparse-checkout: |
          hub/
          deployments/${HUB}

    - name: see if the correct dir has been checked out, and the requirements have been installed
      run: |
        ls -la
        tree

    # Lets us monitor disks getting full as images get bigger over time
    - name: Show how much disk space is left
      run: df -h
