name: Create datahub PR
on:
  workflow_run:
      workflows: ['Build and push container image']
      types: [completed]
      branches:
        - main

jobs:
  create-pr:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      HUB: ${{ vars.HUB }}
      IMAGE: ${{ vars.IMAGE }}

    steps:
      - name: cleanup disk space
        run: |
          sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc
          df -h

      - name: Generate the image name
        run: |
          IMAGE="ucb-datahub-2018/user-images/${HUB}-user-image"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Test if vars works
        run: |
          echo "with vars:"
          echo ${{ vars.IMAGE }}
          echo "no vars:"
          echo ${IMAGE}

      - name: Checkout
        uses: actions/checkout@v4

      - name: Display free space
        run: |
          echo "Free space:"
          df -h

      - name: Checkout files in repo
        uses: actions/checkout@v4
        with:
          repository: 'berkeley-dsep-infra/datahub'
          sparse-checkout: |
            hub/
            deployments/${HUB}

      - name: download artifact with image tag
        uses: actions/download-artifact@v4
        with:
          name: image-tag.txt
          path: ./

      - name: see if the correct dir has been checked out, and the requirements have been installed
        run: |
          ls -la
          tree

      # Lets us monitor disks getting full as images get bigger over time
      - name: Show how much disk space is left
        run: df -h