name: Build and test container image

on:
  pull_request:
env:
  HUB: logodev

jobs:
  test-build:
    runs-on: ubuntu-latest
    env:
      DOCKER_CONFIG: $HOME/.docker
    steps:
      - name: Test if vars works
        run: |
          echo "with vars:"
          echo ${{ vars.HUB }}
          echo "with env:"
          echo ${{ env.HUB }}
          echo "plain old env var:"
          echo ${HUB}
          echo "docker config for sanity:"
          echo ${DOCKER_CONFIG}

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'

      - name: Checkout files in repo
        uses: actions/checkout@v4

      - name: See if the image config changed
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
            files: |
              **.bash
              **.py
              **.r
              **.R
              **.sh
              **.txt
              **.toml
              **.yaml
              **.yml
              Dockerfile
              infra-requirements.txt
              Pipfile**
              postBuild
              requirements.txt
              setup.py
              start
            files_ignore: |
              .github/**
              images/**

      - name: What files changed?
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
            CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
            echo "One or more image file(s) has changed:"
            echo "$CHANGED_FILES"

      - name: Build and test the image if any image file changed
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: jupyterhub/repo2docker-action@master
        with:
          REPO_DIR: /srv/repo
          NO_PUSH: true

      # Lets us monitor disks getting full as images get bigger over time
      - name: Show how much disk space is left
        run: df -h
